server:
  port: 9999
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3305/study
    username: root
    password:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create

REST_API_KEY : ""